#! /bin/sh

# Start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Start polybar
$HOME/.config/polybar/launch.sh

# Start picom
picom --config ~/.config/picom/picom.conf &

# Set background
feh --bg-scale ~/Pictures/wallpaper.jpg

# Set key repeat rate and delay
xset r rate 175 60

bspc monitor -d terminals firefox spotify files extra
bspc config border_width          2
bspc config focused_border_color  "#E0FFFF"
bspc config window_gap            25
bspc config presel_feedback_color "#E0FFFF"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true
